### ISSUE TITLE
Thanks for showing this! Can you add a license?

### ISSUE THREAD

**Issue by mrmcduff** [myeongjae-kim/next-js-with-typescript-valid-app-type#1]
Thanks for posting about this - I found your example via a thread you posted in about how to properly type the `_app.tsx` file for a Next repository. Would you mind adding a license to your repo so that others can fork / copy it appropriately? I'd suggest the MIT license (just copy and paste it into a LICENSE.md file at the root of your repo), but anything from https://choosealicense.com/ would do.

I always prefer to cite where I find answers, but I'd be restricted from using this in projects if it wasn't legally covered.

**Comment by myeongjae-kim** [comment]
Sure. I've copied license.md from Next.js project. I am glad to hear that this repo helps you😀

**Comment by mrmcduff** [comment]
Thanks!
